sqlDialects=postgresql,hsqldb
validateModels=false
useCache=true
frontendType=react
defaultLanguage=hu-HU
tablePageLimit=10
javaCompiler=ecj
#dockerPrometheusJmxExporterAgentVersion=0.20.0
#dockerElasticApmAgentVersion=1.46.0
#dockerNewrelicAgentVersion=8.9.0
dockerTraefikImage=traefik
dockerTraefikTag=v2.9.7
dockerKeycloakImage=quay.io/keycloak/keycloak
dockerKeycloakTag=26.1.2
dockerPostgresImage=postgres
dockerPostgresTag=16.2
generateInterceptorModule=true
generateApplicationModule=true
generateSdkModule=true
generateInternalModule=true
generateRestModule=true
generateFrontendModule=true
generateE2eModule=false
generateDockerModule=true
generateSchemaModule=true
generateKarafModule=true
generateLauncherModule=false

generateKeycloakTheme=true
generateSingleActorApplication=true
generateOpenApiAnnotations=true
baseUrl=http://localhost:8181
authenticationUrl=http://localhost:8080/auth
specificationVersionNumber=1.0.0
formatJavaCodes=true
