
#######################################################################
# G E N E R A T E D    F I L E
# ------------------------------
# Path expression: 'pubspec.yaml'
# Template name: pubspec.yaml.hbs
# Application: edemokracia::admin::Admin

name: edemokracia
description: UI for Edemokracia applications.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    cupertino_icons: ^1.0.2
    # dynamic_widget: ^2.0.1
    dartz: ^0.9.2
    auto_size_text: ^2.1.0
    dio: '>=3.0.3 <4.0.0'
    mobx: ^1.2.1+4
    flutter_mobx: ^1.1.0+2
    provider: ^4.3.3
    path_to_regexp: ^0.4.0

    get_it: ^5.0.6
    auto_route: ^0.6.9
    injectable: ^1.1.0
    universal_html: ^1.2.4
    universal_platform: ^0.1.3
    shared_preferences: ^2.0.1
    flutter_breadcrumb: ^0.1.2
    intl: ^0.17.0
    uuid: ^2.2.2
    quiver: ^2.1.5
    clipboard: ^0.1.2+8
    judo_icon_helper:
        git:
            url: git@github.com:BlackBeltTechnology/judo_icon_helper
            ref: rel/2.0
    judo_flutter_components:
        git:
            url: git@github.com:BlackBeltTechnology/judo-flutter-components.git
            ref: rel/1.22
    flutter_appauth_web:
        git:
            url: git@github.com:BlackBeltTechnology/flutter-appauth-web.git
            ref: rel/1.0
    mime_type: ^0.3.2
    file_picker: ^2.1.7

dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner: ^1.11.1
    mobx_codegen: ^1.1.2
    auto_route_generator: ^0.6.9
    injectable_generator: ^1.1.0
    intl_translation: ^0.17.7

dependency_overrides:
    intl: 0.17.0
    analyzer: 0.41.0
    dart_style: 1.3.10

flutter:
    assets:
        - assets/ninja.png
        - assets/judo-color-logo.png

    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    # assets:
    #   - images/a_dot_burr.jpeg
    #   - images/a_dot_ham.jpeg


    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
    fonts:
#        - family: Roboto
#          fonts:
#              - asset: fonts/Roboto-Regular.ttf

        - family: SourceSansPro
          fonts:
              - asset: fonts/SourceSansPro-Regular.ttf
              - asset: fonts/SourceSansPro-Italic.ttf
                style: italic

              - asset: fonts/SourceSansPro-ExtraLight.ttf
                weight: 100
              - asset: fonts/SourceSansPro-ExtraLight.ttf
                weight: 200
              - asset: fonts/SourceSansPro-Light.ttf
                weight: 300
              - asset: fonts/SourceSansPro-Regular.ttf
                weight: 400
              - asset: fonts/SourceSansPro-SemiBold.ttf
                weight: 500
              - asset: fonts/SourceSansPro-SemiBold.ttf
                weight: 600
              - asset: fonts/SourceSansPro-Bold.ttf
                weight: 700
              - asset: fonts/SourceSansPro-Black.ttf
                weight: 800
              - asset: fonts/SourceSansPro-Black.ttf
                weight: 900

              - asset: fonts/SourceSansPro-ExtraLightItalic.ttf
                style: italic
                weight: 100
              - asset: fonts/SourceSansPro-ExtraLightItalic.ttf
                style: italic
                weight: 200
              - asset: fonts/SourceSansPro-LightItalic.ttf
                style: italic
                weight: 300
              - asset: fonts/SourceSansPro-Italic.ttf
                style: italic
                weight: 400
              - asset: fonts/SourceSansPro-SemiBoldItalic.ttf
                style: italic
                weight: 500
              - asset: fonts/SourceSansPro-SemiBoldItalic.ttf
                style: italic
                weight: 600
              - asset: fonts/SourceSansPro-BoldItalic.ttf
                style: italic
                weight: 700
              - asset: fonts/SourceSansPro-BlackItalic.ttf
                style: italic
                weight: 800
              - asset: fonts/SourceSansPro-BlackItalic.ttf
                style: italic
                weight: 900
